baseURL = 'https://example.org/'
languageCode = 'en-us'

title = 'JPJULIAO'
name = 'JPJULIAO'
author = "Juan Pablo Juliao"
copyright = "© JPJuliao IT Solutions."

theme = 'DoIt'
[menus]
  [[menus.main]]
    name = 'About'
    url = '/about'